import { Poppins } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Navbar from "./component/Navbar";

const poppins = Poppins({weight:"500", subsets: ["latin"] });

export const metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <Navbar/>

        {children}
        </body>
    </html>
  );
}
