import React from 'react'

export const metadata = {
    title: "My Contact",
    description: "Generated by create next app",
  };

const contact = () => {
  return (
    <div>contact</div>
  )
}

export default contact