import Link from 'next/link';
import React from 'react'
import { sessionToken } from '../util/session';
import { redirect } from 'next/navigation';

export const metadata = {
    title: "My Contact",
    description: "Generated by create next app",
  };

const contact = () => {
  //2nd type---> to restrict the route i.e Private route 
  let data=sessionToken;
  if(data){
    redirect('/')
  }
  return (
    <div>This is Contact Page
      <Link href={`/contact/${34}`}>contact</Link>
    </div>
  )
}

export default contact